---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate--v1-configmap
  failurePolicy: Fail
  name: vconfigmap.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - DELETE
    resources:
    - configmaps
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-labels-shahaf-com-v1alpha1-namespacelabel
  failurePolicy: Fail
  name: vnamespacelabel-v1alpha1.kb.io
  rules:
  - apiGroups:
    - labels.shahaf.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - namespacelabels
  sideEffects: None
