apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: namespacelabel
    app.kubernetes.io/managed-by: kustomize
  name: webhook-server
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook-server-role
rules:
- apiGroups:
  - labels.shahaf.com
  resources:
  - namespacelabels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: namespacelabel
    app.kubernetes.io/managed-by: kustomize
  name: webhook-server-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webhook-server-role
subjects:
- kind: ServiceAccount
  name: webhook-server
  namespace: system 