apiVersion: labels.shahaf.com/v1alpha1
kind: NamespaceLabel
metadata:
  labels:
    app.kubernetes.io/name: namespacelabel
    app.kubernetes.io/managed-by: kustomize
  name: labels  # Fixed name for singleton pattern - only "labels" is allowed
  namespace: default
spec:
  # Labels are applied to the same namespace as this CR (default) for security
  # Only one NamespaceLabel CR named "labels" is allowed per namespace
  labels:
    environment: "development"
    team: "platform"
    managed-by: "namespacelabel-operator"
  
  # Protection configuration - prevent overwriting important management labels
  protectedLabelPatterns:
    - "kubernetes.io/*"          # Protect all kubernetes.io labels
    - "*.k8s.io/*"              # Protect all k8s.io domain labels
    - "pod-security.kubernetes.io/*"  # Protect pod security labels
  
  # Protection mode - skip protected labels silently (default: skip)
  protectionMode: skip
  
  # NOTE: The operator enforces a singleton pattern - only one NamespaceLabel CR 
  # named "labels" is allowed per namespace for operational simplicity.
