apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "namespacelabel.labels" . | nindent 4 }}
  name: {{ include "namespacelabel.namePrefix" . }}{{ include "namespacelabel.namePrefix" . }}protection-config
  namespace: {{ .Values.namespace.name }}
data:
  mode: {{ .Values.protection.mode }}
  patterns: |
{{- range .Values.protection.patterns }}
    - {{ . | quote }}
{{- end }}
