# ServiceAccount is in serviceaccount.yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
{{- include "namespacelabel.labels" . | nindent 4 }}
  name: {{ include "namespacelabel.namePrefix" . }}leader-election-role
  namespace: {{ .Values.namespace.name }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "namespacelabel.namePrefix" . }}manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - labels.shahaf.com
  resources:
  - namespacelabels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - labels.shahaf.com
  resources:
  - namespacelabels/finalizers
  verbs:
  - update
- apiGroups:
  - labels.shahaf.com
  resources:
  - namespacelabels/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
{{- include "namespacelabel.labels" . | nindent 4 }}
  name: {{ include "namespacelabel.namePrefix" . }}metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
{{- include "namespacelabel.labels" . | nindent 4 }}
  name: {{ include "namespacelabel.namePrefix" . }}namespacelabel-editor-role
rules:
- apiGroups:
  - labels.shahaf.com
  resources:
  - namespacelabels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - labels.shahaf.com
  resources:
  - namespacelabels/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
{{- include "namespacelabel.labels" . | nindent 4 }}
  name: {{ include "namespacelabel.namePrefix" . }}namespacelabel-viewer-role
rules:
- apiGroups:
  - labels.shahaf.com
  resources:
  - namespacelabels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - labels.shahaf.com
  resources:
  - namespacelabels/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
{{- include "namespacelabel.labels" . | nindent 4 }}
  name: {{ include "namespacelabel.namePrefix" . }}proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
{{- include "namespacelabel.labels" . | nindent 4 }}
  name: {{ include "namespacelabel.namePrefix" . }}leader-election-rolebinding
  namespace: {{ .Values.namespace.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "namespacelabel.namePrefix" . }}leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "namespacelabel.namePrefix" . }}controller-manager
  namespace: {{ .Values.namespace.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
{{- include "namespacelabel.labels" . | nindent 4 }}
  name: {{ include "namespacelabel.namePrefix" . }}manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "namespacelabel.namePrefix" . }}manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "namespacelabel.namePrefix" . }}controller-manager
  namespace: {{ .Values.namespace.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
{{- include "namespacelabel.labels" . | nindent 4 }}
  name: {{ include "namespacelabel.namePrefix" . }}proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "namespacelabel.namePrefix" . }}proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "namespacelabel.namePrefix" . }}controller-manager
  namespace: {{ .Values.namespace.name }}

