apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "namespacelabel.labels" . | nindent 4 }}
    control-plane: controller-manager
  name: {{ include "namespacelabel.namePrefix" . }}controller-manager-metrics-service
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "namespacelabel.labels" . | nindent 4 }}
  name: {{ include "namespacelabel.namePrefix" . }}webhook-service
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - name: webhook-server
    port: 443
    protocol: TCP
    targetPort: {{ .Values.webhook.port }}
  selector:
    control-plane: controller-manager
