apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "namespacelabel.labels" . | nindent 4 }}
  name: {{ include "namespacelabel.namePrefix" . }}controller-manager
  namespace: {{ .Values.namespace.name }}
